version: '3.8'

services:
  audiobook_ripper:
    build: .
    ports:
      - "5009:5000"
    devices:
      - "/dev/cdrom:/dev/cdrom"
      #- "/dev/cdroms/cdrom0:/dev/cdroms/cdrom0"
      #- "/dev/cdroms/cdroma:/dev/cdroms/cdroma"
      #- "/dev/cdroms/cdrom1:/dev/cdroms/cdrom1"
      #- "/dev/cdroms/cdromb:/dev/cdroms/cdromb"
      #- "/dev/cdroms/cdrom2:/dev/cdroms/cdrom2"
      #- "/dev/cdroms/cdromc:/dev/cdroms/cdromc"
      #- "/dev/cdroms/cdrom3:/dev/cdroms/cdrom3"
      #- "/dev/cdroms/cdromd:/dev/cdroms/cdromd"
      #- "/dev/hd0:/dev/hd0"
      #- "/dev/hda:/dev/hda"
      #- "/dev/hd1:/dev/hd1"
      #- "/dev/hdb:/dev/hdb"
      #- "/dev/hd2:/dev/hd2"
      #- "/dev/hdc:/dev/hdc"
      #- "/dev/hd3:/dev/hd3"
      #- "/dev/hdd:/dev/hdd"
      #- "/dev/sg0:/dev/sg0"
      #- "/dev/sga:/dev/sga"
      #- "/dev/sg1:/dev/sg1"
      #- "/dev/sgb:/dev/sgb"
      #- "/dev/sg2:/dev/sg2"
      #- "/dev/sgc:/dev/sgc"
      #- "/dev/sg3:/dev/sg3"
      #- "/dev/sgd:/dev/sgd"
      #- "/dev/cdu31a:/dev/cdu31a"
      #- "/dev/cdu535:/dev/cdu535"
      #- "/dev/sbpcd:/dev/sbpcd"
      #- "/dev/sbpcd0:/dev/sbpcd0"
      #- "/dev/sbpcda:/dev/sbpcda"
      #- "/dev/sbpcd1:/dev/sbpcd1"
      #- "/dev/sbpcdb:/dev/sbpcdb"
      #- "/dev/sbpcd2:/dev/sbpcd2"
      #- "/dev/sbpcdc:/dev/sbpcdc"
      #- "/dev/sbpcd3:/dev/sbpcd3"
      #- "/dev/sbpcdd:/dev/sbpcdd"
      #- "/dev/sonycd:/dev/sonycd"
      #- "/dev/mcd:/dev/mcd"
      #- "/dev/sjcd:/dev/sjcd"
      #- "/dev/cm206cd:/dev/cm206cd"
      #- "/dev/gscd:/dev/gscd"
      #- "/dev/optcd:/dev/optcd"
    volumes:
      - /path/to/audiobooks:/app/audiobooks
      - /path/t0/music:/app/music
    environment:
      - SAVE_DIR=/app/audiobooks
    command: python3 app.py
